import type { AIExplanation as AIExplanationData } from "../types";

interface Props {
  explanation: AIExplanationData;
  modelId?: string | null;
}

export default function AIExplanation({ explanation, modelId }: Props) {
  return (
    <section className="ai-panel" aria-label="AI analysis">
      <div className="ai-header">
        <h3>AI analysis</h3>
        <span className="ai-source">Generated by Amazon Bedrock{modelId ? ` (${modelId})` : ""}</span>
      </div>
      <p className="ai-disclaimer">
        A supplementary explanation of the scanner result above. It does not change the finding or its severity and
        may contain mistakes.
      </p>
      <dl className="detail-list">
        <dt>Explanation</dt>
        <dd>{explanation.explanation}</dd>
        <dt>Impact</dt>
        <dd>{explanation.impact}</dd>
        <dt>Remediation</dt>
        <dd>{explanation.remediation}</dd>
      </dl>
    </section>
  );
}
