from datetime import datetime, timezone
from enum import StrEnum
from typing import Any, Literal

from pydantic import BaseModel, ConfigDict, Field


class Severity(StrEnum):
    CRITICAL = "CRITICAL"
    HIGH = "HIGH"
    MEDIUM = "MEDIUM"
    LOW = "LOW"
    INFO = "INFO"

    @property
    def rank(self) -> int:
        """0 is the most severe."""
        return list(Severity).index(self)


class AIExplanation(BaseModel):
    """Plain-English context generated by Bedrock. Supplementary only: it never changes a finding."""

    model_config = ConfigDict(extra="ignore", str_strip_whitespace=True)

    explanation: str = Field(min_length=1, max_length=2000)
    impact: str = Field(min_length=1, max_length=2000)
    remediation: str = Field(min_length=1, max_length=2000)


class Finding(BaseModel):
    id: str = Field(description="Rule identifier, e.g. EC2-001")
    service: str
    title: str
    severity: Severity
    resource: str
    description: str
    evidence: dict[str, Any] = Field(default_factory=dict)
    recommendation: str
    ai_explanation: AIExplanation | None = None


class ServiceScan(BaseModel):
    """Output of a single service scanner."""

    findings: list[Finding] = Field(default_factory=list)
    resources_scanned: int = 0


class ServiceError(BaseModel):
    """A service scanner that could not run. Messages never include credentials."""

    service: str
    code: str
    message: str


class AIAnalysis(BaseModel):
    """Outcome of the optional Bedrock step. Errors are safe, generic messages."""

    status: Literal["completed", "partial", "unavailable", "skipped"]
    model_id: str | None = None
    findings_selected: int = 0
    findings_explained: int = 0
    errors: list[str] = Field(default_factory=list)


class ScanResult(BaseModel):
    account_id: str
    region: str
    scanned_at: datetime
    resources_scanned: int
    findings_count: int
    severity_counts: dict[str, int]
    findings: list[Finding]
    errors: list[ServiceError] = Field(default_factory=list)
    ai_analysis: AIAnalysis | None = None

    @classmethod
    def build(
        cls,
        account_id: str,
        region: str,
        resources_scanned: int,
        findings: list[Finding],
        errors: list[ServiceError],
    ) -> "ScanResult":
        ordered = sorted(findings, key=lambda f: (f.severity.rank, f.service, f.id, f.resource))
        return cls(
            account_id=account_id,
            region=region,
            scanned_at=datetime.now(timezone.utc),
            resources_scanned=resources_scanned,
            findings_count=len(ordered),
            severity_counts={s.value: sum(f.severity == s for f in ordered) for s in Severity},
            findings=ordered,
            errors=errors,
        )
